# Las aperturas en los días que el llenado en kg superaba los 3 kg

PREFIX medicion: <http://ec2-54-148-16-180.us-west-2.compute.amazonaws.com/ontzia/medicion/>
PREFIX ssn: <http://purl.oclc.org/NET/ssnx/ssn#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

SELECT ?contenedor ?llenado_kg ?aperturas
WHERE { 
    # Fecha y contenedor
    ?obs ssn:observationSamplingTime ?date .
    ?obs ssn:observedBy ?contenedor .     
    
    # llenado en kg
    ?obs ssn:observationResult ?num_kg_depositado .
    ?num_kg_depositado rdf:type medicion:num_kg_depositado .
    ?num_kg_depositado ssn:hasValue ?llenado_kg .

    # aperturas
    ?obs ssn:observationResult ?num_aperturas .
    ?num_aperturas rdf:type medicion:num_aperturas .
    ?num_aperturas ssn:hasValue ?aperturas .

    FILTER (?llenado_kg > 3000)
}
ORDER BY ?aperturas